
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygtypxckflskdhidrswf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlndHlweGNrZmxza2RoaWRyc3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTk2OTEsImV4cCI6MjA2MjM5NTY5MX0.QUk_v9IprgBl57AqpYPcxgnPuxCa6278VNlmV_ltW90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a custom typesafe client that includes our tables
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Create a typed version of supabase.from for each table
// This allows us to use supabase.from('table_name') with proper typing
type Table = 'lab_experiments' | 'memes' | 'events' | 'event_participants' | 
             'archive_items' | 'pixels_canvas' | 'pixels_data' | 'community_members' |
             'forum_categories' | 'forum_posts' | 'forum_topics' | 'profiles';

// This helper function provides proper typing for any table
export function typedFrom<T extends Table>(table: T) {
  return supabase.from(table);
}
