// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygtypxckflskdhidrswf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlndHlweGNrZmxza2RoaWRyc3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTk2OTEsImV4cCI6MjA2MjM5NTY5MX0.QUk_v9IprgBl57AqpYPcxgnPuxCa6278VNlmV_ltW90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);